### ISSUE TITLE
AWS DocumentDB Performance issue with Concurrent Aggregations

### ISSUE THREAD

**Issue by JuanJouglard** [aws-samples/amazon-documentdb-samples#14] opened 2021-06-16 20:23 UTC
I'm working with DocumentDB in AWS, and I've been having troubles when I try to read from the same collection simultaneously from different aggregation queries. 

The issue is not that I cannot read from the database, but rather that it takes a lot of time to complete the queries. It doesn't matter if I trigger the queries simultaneously or one after the other. 

I'm using a Lambda Function with NodeJS to run my code. And I'm using mongoose to handle the connection with the database.

Here's a sample code that I put together to illustrate my problem:

    query1() {
         return Collection.aggregate([...])
    }
     
    query2() {
      return Collection.aggregate([...])
    }

    query3() {
      return Collection.aggregate([...])
    }

It takes the **same time** if I run it using **Promise.all**

```Promise.all([ query1(), query2(), query3() ])```

Than if I run it **waiting for the previous one to finish**

```query1().then(result1 => query2().then(result3 => query3()))```

While if I run each query in different Lambda Executions, it takes significantly less time for each individual query to finish (Between 1 and 2 seconds).

So if they were running in parallel the execution should be finished with the time of the query that takes the most time (2 seconds), and not take 7 seconds, as it does now.

So my guessing is that the instance of DocumentDB is running the queries in sequence no matter how I send them. In the collection there are around **19,000** documents with a total size of almost **25Mb**.

When I check the metrics of the instance, the **CPUUtilization** is barely over **8%** and the **RAM** available only drops by **20Mb**. So I don't think the problem of the delay has to do with the size of the instance.

Do you know why DocumentDB is behaving like this? Is there a configuration that I can change to run the aggregations in parallel?

**Comment by tmcallaghan** [comment] 2021-06-24 18:20
@JuanJouglard can you run the 3 queries simultaneously via 3 individual mongo shell sessions? This will help narrow the investigation.

**Comment by JuanJouglard** [comment] 2021-06-25 21:15
Thanks for the reply!

You mean running the queries using something like 3 different AWS **Cloud9** terminals, or creating 3 different connection within the same Lambda and use each connection to run a query?

I tried the later option and it didn't help with the time issue. Because it seems that the creation of one connection blocks the creation of others. For example: 
 - Time elapsed to create the **first** connection: 1.3 seconds
 - Time elapsed to create the **second** connection: 1.6 seconds
 - Time elapsed to create the **third** connection: 2.1 seconds

This said, the time to complete each query does seem to be the same running only one individually or running the three queries together (e.g. query1 takes 2.1 seconds to run individually and it takes the roughly same when ran concurrently with query2 and query3). 

Overall, there's still an issue with the duration because now the concurrency problem seems to happen on the connection side.

**Comment by tmcallaghan** [comment] 2021-06-28 13:46
@JuanJouglard Please anonymize and paste your lambda code here, I need to see all of it to properly diagnose your issue.

**Comment by JuanJouglard** [comment] 2021-06-28 20:55
Here's the code with the actual queries and connection to the database, all this code runs inside a Lambda Function:

- /db/index.js
```
/* Database Connection */
const mongoose = require("mongoose")

const local = !process.env.AWS_EXECUTION

let retrieveDBCredentials = () => {
  return Promise.resolve({});
};

if (!local) 
    retrieveDBCredentials = require("./secret-manager").retrieveDBCredentials // Uses AWS Secret Manager to get credentials for the database


retrieveDBCredentials().then((secret) => {
    const url = local ? 'mongodb://localhost/test' : `mongodb://${secret.username}:${secret.password}@${secret.host}:${secret.port}/database?retryWrites=false`;
    const config = local ? {
	useUnifiedTopology: true,
	useNewUrlParser: true,
	useFindAndModify: true
    } : {
	tls: true,
	tlsCAFile: "./db/rds-combined-ca-bundle.pem",
	useUnifiedTopology: true,
	useNewUrlParser: true,
	useFindAndModify: true
    }

    mongoose.connect(url, config)
})
```

Sessions schema

```
const mongoose = require('mongoose')

const { Schema } = mongoose;

const itemSchema = new Schema({
    turn: Number,
    input: String,
    output: String,
    timestamp: Date
})

const sessionsSchema = new Schema({
  sessionId: String,
  date: Date,
  userId: String,
  groupId: String,
  array: [itemSchema],
});

sessionsSchema.index({ sessionId: 1, date: 1 }, { unique: true })

module.exports = mongoose.model('Sessions', sessionsSchema)
```
Queries

```
const Sessions = require("./models/sessions")

export const querySessions = (fromDate, toDate) => (queries) => {
    return Sessions.aggregate([
             {
                 $match: {
                    date: {$gt: fromDate, $lt: toDate}
                 }
             },
             ...queries
   ])
}

export const withOneInputMessage = (querySessions) => {
       return querySessions([
      {
        $project: {
          collectionId: 1,
          array: 1,
          last: { $arrayElemAt: ["$array", -1] },
        },
      },
      {
        $match: {
          $and: [
            {
              array: { $size: 1 },
            },
            {
              "last.dtc": 1,
            },
          ],
        },
      },
      {
        $count: "onlyOneMessage",
      },
    ]);

} 
 const TIME_INTERVAL = 10
  export const getTimePerSession = async (querySessions) => {
    return querySessions([
      {
        $addFields: {
          lastItem: {
            $arrayElemAt: ["$array", -1],
          },
        },
      },
      {
        $project: {
          collectionId: 1,
          time: {
                $subtract: [
                  {
                    $arrayElemAt: ["$array.timestamp", -1],
                  },
                  {
                    $arrayElemAt: ["$array.timestamp", 0],
                  },
                ]
          },
        },
      },
      {
        $match: {
          time: { $gt: 0, $lt: 490000 },
        },
      },
      {
        $group: {
          _id: {
            $multiply: [
              {
                $divide: [
                  {
                    $subtract: [
                      "$time",
                      { $mod: ["$time", TIME_INTERVAL * 1000] },
                    ],
                  },
                  TIME_INTERVAL * 1000,
                ],
              },
              TIME_INTERVAL,
            ],
          },
          count: { $sum: 1 },
        },
      },
      {
        $sort: {
          _id: 1,
        },
      },
    ]).then((result) => {
      return result.map(({ _id, count }) => {
        return {
          count,
          range: _id + "s - " + (_id + TIME_INTERVAL - 1) + "s",
        };
      });
    });


  export const getSessionsPerDay: async (querySessions) => {
    return querySessions([
      {
        $group: {
          _id: {
              $dayOfYear: "$date",
          },
          count: { $sum: 1 },
          first: { $min: "$date" },
        },
      },
      { $project: { date: "$first", count: 1, _id: 0 } },
      {
        $sort: {
          date: 1,
        },
      },
    ])

  export const getItemDayOfTheWeek: async (querySessions) => {
    return querySessions([
      { $unwind: "$array" },
      {
        $group: {
          _id: { $dayOfWeek: "$array.timestamp" },
          count: { $sum: 1 },
        },
      },
      {
        $sort: {
          _id: 1,
        },
      }
    ]);
  },

```
Lambda handler that runs the queries

```
exports.handler = () => {
      const aggregateSessions = querySessions(
        req.query.fromDate,
        req.query.toDate
      );


      return Promise.all([
          withOneInputMessage(aggregateSessions),
          getTimePerSession(aggregateSessions),
          getSessionsPerDay(aggregateSessions),
          getItemDayOfTheWeek(aggregateSessions)
      ]);

}
     
```
Let me know if you find any issues. Thanks!

**Comment by tmcallaghan** [comment] 2021-06-29 13:42
The mongoose documentation states that the default poolsize is 5 so you code seems to be correct. Can you try a few things:
1. Add "poolSize: 10" to your connection config and repeat your experiment multiple times.
2. Create 4 mongoose connections in index.js, use each of the 4 in the 4 async functions.

**Comment by JuanJouglard** [comment] 2021-06-29 22:05
I tried setting the poolSize to 10 and it doesn't change the elapsed time. Although I don't think that the change is being applied to the connection, because if I set it to 1 it also doesn't change the time, so it seems that it's doesn't matter the value of poolSize it always executes the queries the same way. Not sure if I'm not setting it correctly or if that configuration is not supported by DocumentDB.

This is how I'm setting the attribute in the config object:

```
module.exports = () => {
    return retrieveDBCredentials().then((secret) => {
            const url = local ? 'mongodb://localhost/test' : `mongodb://${secret.username}:${secret.password}@${secret.host}:${secret.port}/database?retryWrites=false`;
            const config = local ? {
        	useUnifiedTopology: true,
        	useNewUrlParser: true,
        	useFindAndModify: true
            } : {
            	tls: true,
            	tlsCAFile: "./db/rds-combined-ca-bundle.pem",
            	useUnifiedTopology: true,
            	useNewUrlParser: true,
            	useFindAndModify: true,
            	poolSize: 10,
            }
    
        return mongoose.createConnection(url, config);
})

}

```

On the other hand, I tried creating one connection per query, but it also doesn't affect the time. Because creating each connection (in parallel with others) takes longer than creating only one, and then the querying time is about the same as running only on one connection for all the queries. I used the createConnection method to create multiple connections, and then I used connection.model("Sessions", sessionsSchema) to run the aggregations.

**Comment by tmcallaghan** [comment] 2021-06-30 12:48
Given that your code can run locally I assume you've also executed it against a local running MongoDB server. What sort of timings did you measure in that configuration?

I suspect you need to restructure your code to create a single Mongoose connection then share it in your code. You also want the connection to be retained between executions of the lambda, otherwise your Lambda call will always be no faster than the time to create the connection _plus_ the time of the queries. The Mongoose documentation regarding Lambda is helpful -> https://mongoosejs.com/docs/lambda.html.

Beyond these ideas is it possible for you to put your code into a GitHub repo so I can attempt to reproduce this myself?

**Comment by JuanJouglard** [comment] 2021-07-02 22:36
Yes, I have an instance of a MongoDB server running locally and the timings I get when I execute the same queries (with roughly the same documents) against my local versions are minimal (in the order of ms, at most, it takes 500ms). So, I guess that the queries are computationally viable.

Regarding the usage of a shared connection among different executions of the Lambda, that definitely helps and improves the timings. Thanks for that suggestion!
Although I think the base problem of parallelization of queries persists, given that even using a shared connection between queries I still get the same duration no matter if I trigger them in parallel or sequence.

For the Github Repo, you mean the Lambda code or a CloudFormation Template? I still have not put together a template with the services that I'm using.

**Comment by tmcallaghan** [comment] 2023-04-21 14:59
Closing due to age.

**Closed by tmcallaghan** 2023-04-21 14:59 UTC
